<template>
    <div class="beModal text-center">
        <div class="beModal__header">
            <div class="beModal__close">
                <div slot="top-right">
                    <button @click="$modal.hide('modal-two-factor-code')">
                        <i class="icon-close"></i>
                    </button>
                </div>
            </div>
        </div>
        <div class="beModal__body">
            <h2 class="beModal__title">{{'Enabling two-factor authentication'}}</h2>
            <div class="mb30">
                <beInput class="full-width" placeholder="Type your 2-factor Authentication code"></beInput>
                <p class="text-left beModal__info">The 2FA code is generated by an authentication app on your mobile device. For more information click <a href="#">here</a>.</p>
            </div>
            <beButton
                type="button"
                title="Enable"
                :shadow="true"
            ></beButton>
        </div>
        <div class="beModal__footer">
        </div>
    </div>
</template>
<script>
export default {
    data: ()=>({
        resetType: 1
    })
}
</script>
<style lang="scss">
.beModal__info{
    font-size: 14px;
    margin-top: 10px;
    color: rgba(#0B111A, .5);
    a{
        color: #2864FF;
    }
}
</style>